server:
  servlet:
    context-path: /
  port: 8888


spring:
  application:
    name: galaxy-gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:9991
          predicates:
            - Path=/login